import type { Metadata } from "next";
import { Big_Shoulders_Display, Lexend_Deca } from "next/font/google";
import "./globals.css";

const lexend = Lexend_Deca({
  subsets: ["latin"],
  weight: ["400"],
});

const bigShoulders = Big_Shoulders_Display({
  subsets: ["latin"],
  weight: ["700"],
});

export const metadata: Metadata = {
  title: "3 Column Preview Card",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lexend.className} ${bigShoulders.className} text-[15px] antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
